"""Integration tests for bcsvCompare CLI.

Tests: help, combining modes, tolerance, ranges, verbose, errors, coercion,
precision guard, string-to-value.

Exit code: 0 = identical, 1 = different, 2 = error.
"""

import csv
import subprocess
import tempfile
from pathlib import Path

import pytest

from helpers import run_tool


# ── Fixtures ─────────────────────────────────────────────────────────────────


@pytest.fixture(scope="module")
def compare_data(tmp_path_factory, tools):
    """Same-type files generated by bcsvGenerator for basic tests."""
    d = tmp_path_factory.mktemp("compare")

    sensor_a = d / "sensor_a.bcsv"
    sensor_b = d / "sensor_b.bcsv"
    run_tool(tools["bcsvCompare"], "--help")  # smoke
    run_tool(tools["bcsvGenerator"], "-p", "sensor_noisy", "-n", "100", "-o", sensor_a)
    run_tool(tools["bcsvGenerator"], "-p", "sensor_noisy", "-n", "100", "-o", sensor_b)

    mixed = d / "mixed.bcsv"
    run_tool(tools["bcsvGenerator"], "-p", "mixed_generic", "-n", "100", "-o", mixed)

    sensor50 = d / "sensor50.bcsv"
    run_tool(tools["bcsvGenerator"], "-p", "sensor_noisy", "-n", "50", "-o", sensor50)

    return {
        "sensor_a": sensor_a,
        "sensor_b": sensor_b,
        "mixed": mixed,
        "sensor50": sensor50,
        "dir": d,
    }


def _csv_to_bcsv(tool_path: Path, *, csv_data: str, bcsv_path: Path) -> None:
    """Helper: write CSV → convert to BCSV via csv2bcsv."""
    import tempfile as _tmp

    csv_file = Path(_tmp.mktemp(suffix=".csv"))
    try:
        csv_file.write_text(csv_data)
        subprocess.run(
            [str(tool_path), "--overwrite", str(csv_file), str(bcsv_path)],
            capture_output=True,
            check=True,
        )
    finally:
        csv_file.unlink(missing_ok=True)


def _cast_col_type(bcsv_path: Path, col_type: str, tools) -> None:
    """Force column types of a BCSV file in place via bcsvCast --static."""
    subprocess.run(
        [str(tools["bcsvCast"]), "--static", col_type, "--in-place", str(bcsv_path)],
        capture_output=True,
        check=True,
    )


def _assert_col_type(bcsv_path: Path, expected_type: str, tools) -> None:
    """Assert that column 0 of a BCSV file has the expected inferred type.
    Uses bcsvHeader to verify — prevents the regression test from silently
    degenerating if csv2bcsv inference changes."""
    r = subprocess.run(
        [str(tools["bcsvHeader"]), str(bcsv_path)],
        capture_output=True,
        text=True,
    )
    for line in r.stdout.split("\n"):
        parts = line.split()
        if parts and parts[0] == "0":  # first column
            actual = parts[2] if len(parts) > 2 else "<unknown>"
            assert actual == expected_type, (
                f"Column 0 type mismatch: expected {expected_type}, got {actual}"
            )
            return
    raise AssertionError(f"Could not find column 0 header in bcsvHeader output")


def _typed_files(
    tmp_dir: Path,
    csv_a: str,
    csv_b: str,
    tools,
    suffix: str = "",
):
    """Convert two CSV strings to BCSV and return (a.bcsv, b.bcsv) paths."""
    bcsv_a = tmp_dir / f"typed_a{suffix}.bcsv"
    bcsv_b = tmp_dir / f"typed_b{suffix}.bcsv"
    _csv_to_bcsv(tools["csv2bcsv"], csv_data=csv_a, bcsv_path=bcsv_a)
    _csv_to_bcsv(tools["csv2bcsv"], csv_data=csv_b, bcsv_path=bcsv_b)
    return bcsv_a, bcsv_b


@pytest.fixture(scope="module")
def coercion_data(tmp_path_factory, tools):
    """Cross-type BCSV files produced via csv2bcsv type inference."""
    d = tmp_path_factory.mktemp("coerce")

    # --- INT8 vs UINT32 (same value 42) ---
    int_csv = "v\n42\n43\n"  # inferred uint8/small int
    uint_csv = f"v\n{42}\n{65000}\n"  # inferred uint16+
    ci8, cu32 = _typed_files(d, int_csv, uint_csv, tools, suffix="_i8_u32")

    # --- INT8 vs UINT8 identical values ---
    pos_csv = "v\n42\n"
    pos2_csv = "v\n42\n"
    cpos_a, cpos_b = _typed_files(d, pos_csv, pos2_csv, tools, suffix="_pos")

    # --- INT32(-1) vs UINT32 ---
    neg_csv = "v\n-1\n42\n"
    pos_u32_csv = f"v\n{4294967295}\n42\n"
    cneg, cupos = _typed_files(d, neg_csv, pos_u32_csv, tools, suffix="_neg_u32")

    # --- Signed-vs-signed cross-type: INT8(-5) vs INT16(-5) ---
    # Regression test: old cmpEqualInteger promoted b_s to uint64_t inside the
    # ternary, breaking INT8(-5) vs INT16(-5).
    # Strategy: two rows. Both files have row 0 = -5, row 1 = different.
    # Comparing row 0 only exercises the signed-vs-signed path.
    neg8_2r_csv = "v\n-5\n-128\n"  # inferred int8, 2 rows
    neg16_2r_csv = "v\n-5\n-32768\n"  # inferred int16, 2 rows (row 0 is -5)
    cneg_s8_2r, cneg_s16_2r = _typed_files(
        d, neg8_2r_csv, neg16_2r_csv, tools, suffix="_neg_ss"
    )
    # Verify the inference actually produced different signed types.
    # If both inferred to the same type, promoteType returns SAME and the
    # test silently stops guarding the cmpEqualInteger bug it was written for.
    _assert_col_type(cneg_s8_2r, "int8", tools)
    _assert_col_type(cneg_s16_2r, "int16", tools)

    # --- FLOAT vs DOUBLE ---
    float_csv = "v\n1.5\n2.0\n"
    double_csv = "v\n1.5000000000000001\n2.0000000000000000\n"
    cflt, cdbl = _typed_files(d, float_csv, double_csv, tools, suffix="_flt_dbl")

    # The precision-guard pairs below need a genuine INT64/UINT64-vs-DOUBLE
    # comparison. csv2bcsv inference narrows whole-valued float literals like
    # "9007199254740992.0" back to integer types, so the double side is forced
    # with bcsvCast after conversion (lossless here: every b-side value is
    # exactly double-representable) and both sides are asserted to stay honest.

    # --- UINT64 == 2^53 vs DOUBLE (boundary, should pass) ---
    D53 = 9007199254740992
    d53_uint_csv = f"v\n{D53}\n"
    d53_dbl_csv = f"v\n{float(D53)}\n"
    cd53u_a, cd53u_b = _typed_files(
        d, d53_uint_csv, d53_dbl_csv, tools, suffix="_u64_53"
    )
    _cast_col_type(cd53u_b, "double", tools)
    _assert_col_type(cd53u_a, "uint64", tools)
    _assert_col_type(cd53u_b, "double", tools)

    # --- UINT64 > 2^53 (should block without --allow-imprecise) ---
    D53P1 = D53 + 1
    above_uint_csv = f"v\n{D53P1}\n"
    above_dbl_csv = f"v\n{float(D53P1)}\n"
    cabove_u_a, cabove_u_b = _typed_files(
        d, above_uint_csv, above_dbl_csv, tools, suffix="_u64_above53"
    )
    _cast_col_type(cabove_u_b, "double", tools)
    _assert_col_type(cabove_u_a, "uint64", tools)
    _assert_col_type(cabove_u_b, "double", tools)

    # --- INT64 == -2^53 vs DOUBLE (boundary, should pass for negative) ---
    neg_d53_csv = f"v\n{-D53}\n"
    neg_d53_dbl_csv = f"v\n{float(-D53)}\n"
    cd53neg_a, cd53neg_b = _typed_files(
        d, neg_d53_csv, neg_d53_dbl_csv, tools, suffix="_i64_neg53"
    )
    _cast_col_type(cd53neg_b, "double", tools)
    _assert_col_type(cd53neg_a, "int64", tools)
    _assert_col_type(cd53neg_b, "double", tools)

    # --- INT64 < -2^53 (should block without --allow-imprecise) ---
    below_neg_csv = f"v\n{-D53 - 1}\n"
    below_neg_dbl_csv = f"v\n{float(-D53 - 1)}\n"
    cbelow_n_a, cbelow_n_b = _typed_files(
        d, below_neg_csv, below_neg_dbl_csv, tools, suffix="_i64_below53"
    )
    _cast_col_type(cbelow_n_b, "double", tools)
    _assert_col_type(cbelow_n_a, "int64", tools)
    _assert_col_type(cbelow_n_b, "double", tools)

    # --- STRING " 12 " (trimmed → 12) vs UINT(12) ---
    str_ws_csv = "v\n 12 \n"
    num_csv = "v\n12\n"
    cstr_ws, cnum = _typed_files(d, str_ws_csv, num_csv, tools, suffix="_str_ws")

    # --- STRING "12x" (internal garbage) vs UINT(12) ---
    str_garbage_csv = "v\n12x\n"
    str_garbage, gar_num = _typed_files(
        d, str_garbage_csv, num_csv, tools, suffix="_str_gb"
    )

    # --- STRING "3.14" vs DOUBLE(3.14) ---
    str_pi_csv = "v\n3.14\n"
    dbl_pi_csv = "v\n3.14\n"
    cstr_pi, cdbl_pi = _typed_files(d, str_pi_csv, dbl_pi_csv, tools, suffix="_str_pi")

    return {
        "ci8": ci8,
        "cu32": cu32,
        "cneg": cneg,
        "cupos": cupos,
        "cneg_s8_2r": cneg_s8_2r,
        "cneg_s16_2r": cneg_s16_2r,
        "cneg_s8_2r": cneg_s8_2r,
        "cneg_s16_2r": cneg_s16_2r,
        "cflt": cflt,
        "cdbl": cdbl,
        "cd53u_a": cd53u_a,
        "cd53u_b": cd53u_b,
        "cabove_u_a": cabove_u_a,
        "cabove_u_b": cabove_u_b,
        "cd53neg_a": cd53neg_a,
        "cd53neg_b": cd53neg_b,
        "cbelow_n_a": cbelow_n_a,
        "cbelow_n_b": cbelow_n_b,
        "cstr_ws": cstr_ws,
        "cnum": cnum,
        "str_garbage": str_garbage,
        "gar_num": gar_num,
        "cstr_pi": cstr_pi,
        "cdbl_pi": cdbl_pi,
        "cpos_a": cpos_a,
        "cpos_b": cpos_b,
        "dir": d,
    }


# ── Help ─────────────────────────────────────────────────────────────────────


class TestCompareHelp:
    def test_help_output(self, tools):
        r = run_tool(tools["bcsvCompare"], "--help")
        assert "bcsvCompare" in r.stdout
        # New combining-mode keywords
        assert "names" in r.stdout
        assert "types" in r.stdout
        assert "values" in r.stdout
        assert "all" in r.stdout
        # Legacy aliases
        assert "strict" in r.stdout
        assert "compatible" in r.stdout
        assert "value" in r.stdout
        # New options
        assert "--string-to-value" in r.stdout
        assert "--allow-imprecise" in r.stdout


# ── Identical files (default & aliases) ──────────────────────────────────────


class TestIdentical:
    def test_default_all(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 0

    def test_explicit_all(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "all",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 0

    def test_strict_alias(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "strict",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 0

    def test_compatible_alias(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "compatible",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 0

    def test_value_alias(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "value",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 0


# ── Individual modes ─────────────────────────────────────────────────────────


class TestIndividualModes:
    def test_names_only(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "names",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 0

    def test_types_only(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "types",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 0

    def test_values_only(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 0


# ── Combinations ─────────────────────────────────────────────────────────────


class TestCombinations:
    def test_names_types(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "names,types",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 0

    def test_names_values(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "names,values",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 0

    def test_types_values(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "types,values",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 0


# ── Header-only: different row count must pass ───────────────────────────────


class TestHeaderOnlyRowCount:
    def test_names_skip_row_count(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "names",
            compare_data["sensor_a"],
            compare_data["sensor50"],
            check=False,
        )
        assert r.returncode == 0

    def test_types_skip_row_count(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "types",
            compare_data["sensor_a"],
            compare_data["sensor50"],
            check=False,
        )
        assert r.returncode == 0

    def test_names_types_skip_row_count(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "names,types",
            compare_data["sensor_a"],
            compare_data["sensor50"],
            check=False,
        )
        assert r.returncode == 0


# ── Argument order independence ──────────────────────────────────────────────


class TestArgOrder:
    def test_allow_imprecise_before_mode(self, tools, coercion_data):
        before = run_tool(
            tools["bcsvCompare"],
            "--allow-imprecise",
            "--mode",
            "values",
            coercion_data["cabove_u_a"],
            coercion_data["cabove_u_b"],
            check=False,
        )
        after = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            "--allow-imprecise",
            coercion_data["cabove_u_a"],
            coercion_data["cabove_u_b"],
            check=False,
        )
        assert before.returncode == after.returncode
        assert before.returncode == 0


# ── Error cases ──────────────────────────────────────────────────────────────


class TestErrors:
    def test_unknown_mode(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "bogus",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 2

    def test_whitespace_rejected(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "names, types",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 2

    def test_mixed_legacy_new(self, tools, compare_data):
        """Combining legacy alias with keyword must fail."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "strict,names",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 2

    def test_no_args(self, tools):
        r = run_tool(tools["bcsvCompare"], check=False)
        assert r.returncode == 2

    def test_missing_file(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            compare_data["sensor_a"],
            "/tmp/nonexistent_bcsv_compare.bcsv",
            check=False,
        )
        assert r.returncode == 2


# ── Verbose ──────────────────────────────────────────────────────────────────


class TestVerbose:
    def test_verbose_identical(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "-v",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
        )
        assert r.returncode == 0
        assert "Result: identical" in r.stdout

    def test_verbose_different(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "-v",
            compare_data["sensor_a"],
            compare_data["mixed"],
            check=False,
        )
        assert r.returncode == 1
        assert "Result: different" in r.stdout


# ── Ranges ───────────────────────────────────────────────────────────────────


class TestRanges:
    def test_rows_range(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--rows",
            "0:9",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
        )
        assert r.returncode == 0

    def test_cols_range(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--cols",
            "0:1",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
        )
        assert r.returncode == 0

    def test_rows_out_of_bounds(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--rows",
            "200:300",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 2


# ── Coerced values ───────────────────────────────────────────────────────────


class TestCoercedValues:
    def test_values_int_coerce(self, tools, coercion_data):
        """INT8/small-int vs UINT32 with same value — coerce mode, exit 0."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            coercion_data["cpos_a"],
            coercion_data["cpos_b"],
            check=False,
        )
        assert r.returncode == 0

    def test_values_signed_vs_unsigned_negative(self, tools, coercion_data):
        """INT(-1) vs UINT(4294967295) — std::cmp_equal returns false, exit 1."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            coercion_data["cneg"],
            coercion_data["cupos"],
            check=False,
        )
        assert r.returncode == 1

    def test_values_signed_vs_signed_same(self, tools, coercion_data):
        """INT8(-5) vs INT16(-5) — cross-type signed, must exit 0.

        This is the exact regression test for the cmpEqualInteger ternary bug:
        the old code promoted b_s to uint64_t before cmp_equal, turning -5 into
        a huge unsigned value, making cmp_equal(-5, huge) return false.
        """
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            "--rows",
            "0",  # Compare only row 0 where both are -5
            coercion_data["cneg_s8_2r"],
            coercion_data["cneg_s16_2r"],
            check=False,
        )
        assert r.returncode == 0

    def test_values_signed_vs_signed_different(self, tools, coercion_data):
        """INT8(-5) vs INT16(-32768) — cross-type signed with different values, exit 1.

        Row 0 has -5 vs -5 (match), but row 1 has -128 vs -5 (mismatch), so
        overall exit is 1.
        """
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            coercion_data["cneg_s8_2r"],
            coercion_data["cneg_s16_2r"],
            check=False,
        )
        assert r.returncode == 1

    def test_values_float_vs_double(self, tools, coercion_data):
        """FLOAT vs DOUBLE widen to double — exit 0."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            coercion_data["cflt"],
            coercion_data["cdbl"],
            check=False,
        )
        assert r.returncode == 0


# ── Precision guard boundary ─────────────────────────────────────────────────


class TestPrecisionGuard:
    def test_uint64_exactly_2pow53_vs_double(self, tools, coercion_data):
        """UINT64 == 2^53 vs DOUBLE — boundary is exactly representable, exit 0."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            coercion_data["cd53u_a"],
            coercion_data["cd53u_b"],
            check=False,
        )
        assert r.returncode == 0

    def test_uint64_above_2pow53_default(self, tools, coercion_data):
        """UINT64 == 2^53+1 vs DOUBLE, no flag — guard blocks, exit 1."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            coercion_data["cabove_u_a"],
            coercion_data["cabove_u_b"],
            check=False,
        )
        assert r.returncode == 1

    def test_uint64_above_2pow53_allow_imprecise(self, tools, coercion_data):
        """UINT64 == 2^53+1 vs DOUBLE, --allow-imprecise → proceed, exit 0."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            "--allow-imprecise",
            coercion_data["cabove_u_a"],
            coercion_data["cabove_u_b"],
            check=False,
        )
        assert r.returncode == 0

    def test_int64_exactly_neg2pow53_vs_double(self, tools, coercion_data):
        """INT64 == -2^53 vs DOUBLE — negative boundary is exactly representable, exit 0."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            coercion_data["cd53neg_a"],
            coercion_data["cd53neg_b"],
            check=False,
        )
        assert r.returncode == 0

    def test_int64_below_neg2pow53_default(self, tools, coercion_data):
        """INT64 < -2^53 vs DOUBLE, no flag — guard blocks, exit 1."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            coercion_data["cbelow_n_a"],
            coercion_data["cbelow_n_b"],
            check=False,
        )
        assert r.returncode == 1

    def test_int64_below_neg2pow53_allow_imprecise(self, tools, coercion_data):
        """INT64 < -2^53 vs DOUBLE, --allow-imprecise → proceed, exit 0."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            "--allow-imprecise",
            coercion_data["cbelow_n_a"],
            coercion_data["cbelow_n_b"],
            check=False,
        )
        assert r.returncode == 0


# ── String parsing edge cases ────────────────────────────────────────────────


class TestStringParsing:
    def test_string_to_value_whitespace_trimmed(self, tools, coercion_data):
        """STRING ' 12 ' vs numeric 12 — trimmed, exit 0."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            "--string-to-value",
            coercion_data["cstr_ws"],
            coercion_data["cnum"],
            check=False,
        )
        assert r.returncode == 0

    def test_string_to_value_internal_garbage_mismatch(self, tools, coercion_data):
        """STRING '12x' vs numeric 12 — not fully consumed, exit 1."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            "--string-to-value",
            coercion_data["str_garbage"],
            coercion_data["gar_num"],
            check=False,
        )
        assert r.returncode == 1

    def test_string_to_value_float(self, tools, coercion_data):
        """STRING '3.14' vs DOUBLE 3.14 — parses as float, exit 0."""
        r = run_tool(
            tools["bcsvCompare"],
            "--mode",
            "values",
            "--string-to-value",
            coercion_data["cstr_pi"],
            coercion_data["cdbl_pi"],
            check=False,
        )
        assert r.returncode == 0


# ── Tolerance ────────────────────────────────────────────────────────────────


class TestTolerance:
    def test_tolerance(self, tools, compare_data):
        r = run_tool(
            tools["bcsvCompare"],
            "--tolerance",
            "1e-6",
            compare_data["sensor_a"],
            compare_data["sensor_b"],
            check=False,
        )
        assert r.returncode == 0
