#!/usr/bin/env python3
# Copyright (c) 2025 Tobias Weber <weber.tobias.md@gmail.com>
#
# This file is part of the BCSV library.
#
# Licensed under the MIT License. See LICENSE file in the project root
# for full license information.

"""Verify every version stamp in the repository agrees with VERSION.txt.

VERSION.txt is the single source of truth (see cmake/GetGitVersion.cmake). The
manifests below are patched from it at pack time, but they are also committed,
so they drift silently unless something checks them - which is how the Unity
package.json sat at 1.5.3 for nine releases.

The --native check is the one that matters at release time: it loads a built
shared library and asks it what version it thinks it is. Checking the binary
rather than the build inputs is what catches a toolchain that resolved the
version differently from what the release intended.

Usage:
    scripts/check_versions.py                       # check committed manifests
    scripts/check_versions.py --tag v1.5.13         # also require the tag to match
    scripts/check_versions.py --native build/libbcsv_c_api.so
    scripts/check_versions.py --native build/libbcsv_c_api.so --self-contained
    scripts/check_versions.py --python .venv/bin/python  # installed pybcsv
"""

from __future__ import annotations

import argparse
import ctypes
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")


def read_source_of_truth() -> str:
    path = ROOT / "VERSION.txt"
    if not path.exists():
        sys.exit(f"FAIL VERSION.txt missing at {path}")
    version = path.read_text().strip()
    if not VERSION_RE.match(version):
        sys.exit(f"FAIL VERSION.txt contains {version!r}, not a valid X.Y.Z version")
    return version


def check_unity_manifest(expected: str) -> list[str]:
    path = ROOT / "unity" / "package.json"
    if not path.exists():
        return [f"{path.relative_to(ROOT)} not found"]
    found = json.loads(path.read_text()).get("version")
    if found != expected:
        return [f"unity/package.json says {found!r}, expected {expected!r}"]
    return []


def check_csproj(expected: str) -> list[str]:
    path = ROOT / "csharp" / "src" / "Bcsv" / "Bcsv.csproj"
    if not path.exists():
        return [f"{path.relative_to(ROOT)} not found"]
    match = re.search(r"<Version>([^<]+)</Version>", path.read_text())
    if not match:
        return ["csharp/src/Bcsv/Bcsv.csproj has no <Version> element"]
    if match.group(1) != expected:
        return [f"Bcsv.csproj says {match.group(1)!r}, expected {expected!r}"]
    return []


def check_python_version_file(expected: str) -> list[str]:
    """python/VERSION.txt is a sync_headers.py artifact, not a manifest.

    It exists only so an sdist -- which has no repository root above it -- can
    still resolve a version (see python/CMakeLists.txt).  It used to be
    committed, and drifted three releases behind while this script reported
    "all version stamps agree": exactly the blind spot that shipped v1.5.12
    with 1.5.11 natives.  It is now gitignored, but if one is present it must
    agree, because that is the copy an sdist build would use.
    """
    path = ROOT / "python" / "VERSION.txt"
    if not path.exists():
        return []  # regenerated by sync_headers.py at sdist time
    found = path.read_text().strip()
    if found != expected:
        return [
            f"python/VERSION.txt says {found!r}, expected {expected!r} - an sdist "
            f"built from this tree would stamp the wrong version. Run "
            f"python/sync_headers.py, or delete the file (it is generated)."
        ]
    return []


def check_readme_version(expected: str) -> list[str]:
    """README.md advertises the current version to anyone landing on the repo.

    Nothing patches it at pack time, so it drifts silently exactly like the
    manifests above did -- it sat at v1.5.8 for seven releases while this script
    reported "all version stamps agree", because it was not looking.
    """
    path = ROOT / "README.md"
    if not path.exists():
        return [f"{path.name} not found"]
    match = re.search(r"^\*\*Current Version:\*\* v(.+)$", path.read_text(),
                      re.MULTILINE)
    if not match:
        return [
            "README.md has no '**Current Version:** vX.Y.Z' line - if it moved, "
            "update check_readme_version() rather than dropping the check"
        ]
    if match.group(1) != expected:
        return [f"README.md says v{match.group(1)}, expected v{expected}"]
    return []


def check_tag(expected: str, tag: str) -> list[str]:
    if tag != f"v{expected}":
        return [
            f"git tag {tag!r} does not match VERSION.txt {expected!r}; "
            f"bump VERSION.txt in a commit before tagging (see VERSIONING.md)"
        ]
    return []


def check_native(expected: str, lib_path: str) -> list[str]:
    """Load the built library and ask it for its own version string.

    Loading is not decoration: the dlopen fails on any unresolved import,
    and the layout create/destroy round-trip exercises real construction and
    destruction into the runtime the artifact carries (the paths behind
    docs/adr/0007). A symbol scan alone sees neither."""
    path = Path(lib_path)
    if not path.exists():
        return [f"native library not found: {lib_path}"]
    try:
        lib = ctypes.CDLL(str(path.resolve()))
    except OSError as exc:
        return [f"could not load {lib_path}: {exc}"]
    lib.bcsv_version.restype = ctypes.c_char_p
    found = lib.bcsv_version().decode()
    if found != expected:
        return [
            f"{lib_path} reports version {found!r}, expected {expected!r} - "
            f"the build resolved a different version than the release intends"
        ]
    lib.bcsv_layout_create.restype = ctypes.c_void_p
    lib.bcsv_layout_destroy.argtypes = [ctypes.c_void_p]
    handle = lib.bcsv_layout_create()
    if not handle:
        return [f"{lib_path}: bcsv_layout_create returned null"]
    lib.bcsv_layout_destroy(ctypes.c_void_p(handle))
    print(f"  OK   {lib_path} reports {found}, loaded and round-tripped a layout")
    return []


def check_native_self_contained(lib_path: str) -> list[str]:
    """Self-contained packaging artifacts must carry their own C++ runtime:
    a consumer cannot be asked to install one, and a foreign runtime in the
    same process is the interposition failure of docs/adr/0007. Opt-in:
    builds that pair with a host runtime deliberately (local dev, NuGet linux)
    omit the flag."""
    path = Path(lib_path)
    if not path.exists():
        return [f"native library not found: {lib_path}"]
    head = path.read_bytes()[:4]
    if head == b"\x7fELF":
        objdump = shutil.which("objdump")
        if not objdump:
            return [f"objdump not found to check {lib_path}"]
        out = subprocess.run([objdump, "-p", str(path)],
                             capture_output=True, text=True, check=True).stdout
        needed = [ln.split()[1] for ln in out.splitlines()
                  if ln.strip().startswith("NEEDED")]
        bad = [n for n in needed if "libstdc++" in n or "libgcc_s" in n]
        if bad:
            return [f"{lib_path} needs a system C++ runtime ({', '.join(bad)}) "
                    f"- link it with -static-libstdc++ -static-libgcc"]
        print(f"  OK   {lib_path} needs no external C++ runtime")
        return []
    if head == b"MZ":
        dumpbin = shutil.which("dumpbin")
        if not dumpbin:
            vc = os.environ.get("VCToolsInstallDir", "")
            cand = Path(vc) / "bin" / "Hostx64" / "x64" / "dumpbin.exe"
            if vc and cand.exists():
                dumpbin = str(cand)
        if not dumpbin:
            return [f"dumpbin not found to check {lib_path}"]
        out = subprocess.run([dumpbin, "/DEPENDENTS", str(path)],
                             capture_output=True, text=True).stdout
        imports = re.findall(r"^\s+(\S+\.dll)$", out, re.MULTILINE)
        if not imports:
            return [f"dumpbin found no dependencies for {lib_path} "
                    f"- unparseable output, refusing to pass"]
        bad = [i for i in imports
               if re.search(r"MSVCP|VCRUNTIME|api-ms-win-crt", i, re.IGNORECASE)]
        if bad:
            return [f"{lib_path} needs the Visual C++ Redistributable "
                    f"({', '.join(bad)})"]
        print(f"  OK   {lib_path} needs no Visual C++ Redistributable")
        return []
    return []  # Mach-O ships the system libc++ by convention


def check_native_exports(lib_path: str) -> list[str]:
    """ELF artifacts named libbcsv_c_api*: the dynamic table must define
    bcsv_* only (docs/adr/0007). A host that already loaded its own C++
    runtime (Unity player, Mono, CPython) interposes re-exported symbols,
    and one runtime copy then destroys what the other constructed. CTest
    bcsv_c_api_export_surface is the unit-side tripwire; this one runs on
    the release artifact itself, including the package builds that skip
    the test suite.

    The manylinux wheels vendor libstdc++ differently (auditwheel hides the
    vendored symbols), so this checks the C API library, not extensions."""
    path = Path(lib_path)
    if not path.exists() or "bcsv_c_api" not in path.name:
        return []
    if path.read_bytes()[:4] != b"\x7fELF":
        return []  # Mach-O has two-level namespaces, COFF no interposition
    try:
        out = subprocess.run(
            ["nm", "--defined-only", "--extern-only", str(path.resolve())],
            capture_output=True, text=True, check=True,
        ).stdout
    except (subprocess.CalledProcessError, OSError) as exc:
        return [f"nm failed on {lib_path}: {exc}"]
    fields = (ln.split() for ln in out.splitlines() if ln.split())
    stray = [f[-1] for f in fields if not f[-1].startswith("bcsv_")]
    if stray:
        return [f"{lib_path} exports {len(stray)} symbol(s) outside the bcsv_* "
                f"C API ({', '.join(stray[:5])}...) - docs/adr/0007"]
    print(f"  OK   {lib_path} exports only the bcsv_* C API")
    return []


def check_python_package(expected: str, interpreter: str) -> list[str]:
    """Ask the *installed* pybcsv what version INTERPRETER actually imports.

    The sibling of check_native(), for the same reason: an installed Python
    package is a build artifact too, so checking the build inputs says nothing
    about what a benchmark - or a user - will really import.

    Two failure modes, both seen in the wild, both invisible to the manifest
    checks above:

    1. Stale label.  scikit-build-core's editable install auto-rebuilds the
       compiled extension on import but does *not* regenerate `_version.py`, so
       after a release bump the extension carries the NEW code under the OLD
       version string.  A v1.5.17 checkout reported `pybcsv.__version__ ==
       '1.5.16'`: the binary was right and only its label was wrong, which is
       the hardest kind of drift to spot and lands straight in benchmark
       result metadata.

    2. Shadowing.  A stray `pip install -e` into the *user* site (~/.local)
       leaves a .pth pointing at `python/`, so any interpreter outside the venv
       imports the source tree without the compiled extension and dies with
       "partially initialized module 'pybcsv' ... has no attribute
       'DEFAULT_COMPRESSION_LEVEL'".  Its console scripts install into
       ~/.local/bin and win on PATH whenever the venv is not active, so the
       parquet CLIs break in a way that looks like a library bug and survives
       every reinstall of the venv, because that is not where it lives.

    The probe imports the way a real caller would - no -I, no cleaned sys.path -
    because isolating it would hide exactly the shadowing it is here to catch.
    It reports the distribution's install path rather than `pybcsv.__file__`,
    because an editable install resolves `__file__` into the source tree whether
    it is the venv's own or a stray one: the .dist-info location is what tells
    them apart.

    Exact equality is required, which is only meaningful on a release commit:
    setuptools_scm resolves a tagged commit to the tag itself, but a dev tree to
    the *next* version (`1.5.18.dev1` one commit past v1.5.17), so a `.devN`
    string is normal there rather than evidence of staleness. That is why this
    is opt-in, like --native, instead of joining the default manifest sweep.
    """
    probe = r"""
import json, site, sys
out = {}
try:
    import importlib.metadata as md
    dist = md.distribution('pybcsv')
    out['dist_version'] = dist.version
    out['dist_path'] = str(getattr(dist, '_path', '') or dist.locate_file(''))
except BaseException as exc:
    out['dist_error'] = '%s: %s' % (type(exc).__name__, exc)
try:
    out['user_site'] = site.getusersitepackages()
except BaseException:
    out['user_site'] = ''
try:
    import pybcsv
    out['ok'] = True
    out['version'] = pybcsv.__version__
    out['origin'] = getattr(pybcsv, '__file__', '') or ''
except BaseException as exc:
    out['ok'] = False
    out['error'] = '%s: %s' % (type(exc).__name__, exc)
sys.stdout.write(json.dumps(out))
"""
    try:
        proc = subprocess.run([interpreter, "-c", probe],
                              capture_output=True, text=True, timeout=120)
    except (OSError, subprocess.SubprocessError) as exc:
        return [f"could not run {interpreter!r}: {exc}"]
    try:
        info = json.loads(proc.stdout)
    except json.JSONDecodeError:
        detail = (proc.stderr or "").strip().splitlines()
        return [f"{interpreter} could not probe pybcsv: "
                f"{detail[-1] if detail else f'exit status {proc.returncode}'}"]

    where = info.get("dist_path") or info.get("origin") or "unknown location"
    hint = _stray_hint(info)

    if not info.get("ok"):
        return [" ".join(filter(None, [
            f"{interpreter} cannot import pybcsv ({where}): {info.get('error')}.",
            hint or "The package is not importable for this interpreter.",
        ]))]

    found = info.get("version", "")
    if found != expected:
        return [" ".join(filter(None, [
            f"installed pybcsv reports {found!r}, expected {expected!r} ({where}).",
            hint,
            f"If this is the venv's own editable install, it does not regenerate "
            f"its version on auto-rebuild, so the extension may be current and "
            f"only mislabelled - reinstall it: {interpreter} -m pip install -e "
            f"python --no-deps --force-reinstall",
        ]))]

    print(f"  OK   {interpreter} imports pybcsv {found} ({where})")
    return []


def _stray_hint(info: dict) -> str:
    """Name the stray user-site install; it does not announce itself.

    Distinguished by where the *distribution* lives, not by `__file__`: both a
    stray editable install and the venv's own resolve `__file__` into python/.
    """
    dist_path, user_site = info.get("dist_path", ""), info.get("user_site", "")
    if dist_path and user_site and Path(dist_path).is_relative_to(user_site):
        return (f"This is a stray editable install in the user site ({user_site}), "
                f"not the venv's - it shadows the venv for every interpreter "
                f"outside it, and its bcsv2parquet / parquet2bcsv scripts win on "
                f"PATH whenever the venv is inactive. Remove it with: "
                f"pip uninstall pybcsv (from outside the venv).")
    return ""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tag", help="git tag this build claims to be (e.g. v1.5.13)")
    parser.add_argument("--native", action="append", default=[],
                        help="path to a built shared library to load and verify")
    parser.add_argument("--python", nargs="?", const=sys.executable, default=None,
                        metavar="INTERPRETER",
                        help="verify the pybcsv installed for INTERPRETER (default: the "
                             "interpreter running this script). Exact match, so only "
                             "meaningful on a release commit - a dev tree resolves to the "
                             "next version (1.5.18.dev1), not VERSION.txt")
    parser.add_argument("--skip-manifests", action="store_true",
                        help="only run the --tag / --native / --python checks")
    parser.add_argument("--self-contained", action="store_true",
                        help="with --native: also require the library to carry"
                             " its own C++ runtime (no system libstdc++/MSVCP)")
    args = parser.parse_args()

    expected = read_source_of_truth()
    print(f"VERSION.txt: {expected}")

    problems: list[str] = []
    if not args.skip_manifests:
        problems += check_unity_manifest(expected)
        problems += check_python_version_file(expected)
        problems += check_csproj(expected)
        problems += check_readme_version(expected)
    if args.tag:
        problems += check_tag(expected, args.tag)
    for lib in args.native:
        problems += check_native(expected, lib)
        problems += check_native_exports(lib)
        if args.self_contained:
            problems += check_native_self_contained(lib)
    if args.python:
        problems += check_python_package(expected, args.python)

    if problems:
        print(f"\nFAIL {len(problems)} version mismatch(es):", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    print("PASS all version stamps agree")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
