"""Python bindings for the BCSV (Binary CSV) library"""

from collections.abc import Sequence
import enum
from typing import overload


class ColumnType(enum.Enum):
    BOOL = 0

    UINT8 = 1

    UINT16 = 2

    UINT32 = 3

    UINT64 = 4

    INT8 = 5

    INT16 = 6

    INT32 = 7

    INT64 = 8

    FLOAT = 9

    DOUBLE = 10

    STRING = 11

BOOL: ColumnType = ColumnType.BOOL

UINT8: ColumnType = ColumnType.UINT8

UINT16: ColumnType = ColumnType.UINT16

UINT32: ColumnType = ColumnType.UINT32

UINT64: ColumnType = ColumnType.UINT64

INT8: ColumnType = ColumnType.INT8

INT16: ColumnType = ColumnType.INT16

INT32: ColumnType = ColumnType.INT32

INT64: ColumnType = ColumnType.INT64

FLOAT: ColumnType = ColumnType.FLOAT

DOUBLE: ColumnType = ColumnType.DOUBLE

STRING: ColumnType = ColumnType.STRING

class ColumnDefinition:
    def __init__(self, name: str, type: ColumnType) -> None: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

    @property
    def type(self) -> ColumnType: ...

    @type.setter
    def type(self, arg: ColumnType, /) -> None: ...

    def __repr__(self) -> str: ...

class Layout:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: Sequence[ColumnDefinition], /) -> None: ...

    @overload
    def add_column(self, column: ColumnDefinition) -> None: ...

    @overload
    def add_column(self, name: str, type: ColumnType) -> None: ...

    def column_count(self) -> int: ...

    def column_name(self, index: int) -> str: ...

    def column_type(self, index: int) -> ColumnType: ...

    def has_column(self, name: str) -> bool: ...

    def column_index(self, name: str) -> int: ...

    def get_column_names(self) -> list[str]: ...

    def get_column_types(self) -> list[ColumnType]: ...

    def get_column(self, index: int) -> ColumnDefinition: ...

    def __len__(self) -> int: ...

    def __getitem__(self, arg: int, /) -> ColumnDefinition: ...

    def __repr__(self) -> str: ...

class FileFlags(enum.IntEnum):
    NONE = 0

    ZERO_ORDER_HOLD = 1

    NO_FILE_INDEX = 2

    STREAM_MODE = 4

    BATCH_COMPRESS = 8

    DELTA_ENCODING = 16

    def __or__(self, arg: FileFlags, /) -> int: ...

    def __and__(self, arg: FileFlags, /) -> int: ...

    def __invert__(self) -> int: ...

NONE: FileFlags = FileFlags.NONE

ZERO_ORDER_HOLD: FileFlags = FileFlags.ZERO_ORDER_HOLD

NO_FILE_INDEX: FileFlags = FileFlags.NO_FILE_INDEX

STREAM_MODE: FileFlags = FileFlags.STREAM_MODE

BATCH_COMPRESS: FileFlags = FileFlags.BATCH_COMPRESS

DELTA_ENCODING: FileFlags = FileFlags.DELTA_ENCODING

class Writer:
    def __init__(self, layout: Layout, row_codec: str = 'delta') -> None: ...

    def open(self, filename: str, overwrite: bool = False, compression_level: int = 1, block_size_kb: int = 64, flags: FileFlags = FileFlags.BATCH_COMPRESS) -> bool: ...

    def write_row(self, arg: list, /) -> None: ...

    def write_rows(self, arg: list, /) -> None:
        """Write multiple rows efficiently with batching"""

    def close(self) -> None: ...

    def flush(self) -> None: ...

    def is_open(self) -> bool: ...

    def row_count(self) -> int: ...

    def row_codec(self) -> str: ...

    def compression_level(self) -> int: ...

    def layout(self) -> Layout: ...

    def __enter__(self) -> Writer: ...

    def __exit__(self, *args) -> None: ...

    def __repr__(self) -> str: ...

class Reader:
    def __init__(self) -> None: ...

    def open(self, filename: str) -> bool: ...

    def layout(self) -> Layout: ...

    def read_next(self) -> bool: ...

    def close(self) -> None: ...

    def is_open(self) -> bool: ...

    def file_flags(self) -> int: ...

    def compression_level(self) -> int: ...

    def row_pos(self) -> int: ...

    def version_string(self) -> str: ...

    def creation_time(self) -> int: ...

    def count_rows(self) -> int:
        """Count the total number of rows in the file"""

    def row_value(self, column: int) -> object:
        """Get a typed value from the current row by column index"""

    def row_dict(self) -> dict:
        """Get the current row as a dict {column_name: value}"""

    def read_batch(self, batch_size: int = 10000) -> object:
        """
        Read up to batch_size rows into a dict of numpy arrays/lists. Returns None at EOF.
        """

    def read_row(self) -> object: ...

    def read_all(self) -> list: ...

    def __enter__(self) -> Reader: ...

    def __exit__(self, *args) -> None: ...

    def __iter__(self) -> Reader: ...

    def __next__(self) -> object: ...

    def __repr__(self) -> str: ...

def type_to_string(arg: ColumnType, /) -> str:
    """Convert ColumnType to string"""

class CsvWriter:
    def __init__(self, layout: Layout, delimiter: str = ',', decimal_sep: str = '.') -> None: ...

    def open(self, filename: str, overwrite: bool = False, include_header: bool = True) -> bool: ...

    def close(self) -> None: ...

    def is_open(self) -> bool: ...

    def row_count(self) -> int: ...

    def layout(self) -> Layout: ...

    def delimiter(self) -> str: ...

    def decimal_separator(self) -> str: ...

    def __enter__(self) -> CsvWriter: ...

    def __exit__(self, *args) -> None: ...

    def write_row(self, arg: list, /) -> None: ...

    def write_rows(self, arg: list, /) -> None:
        """Write multiple rows efficiently"""

class CsvReader:
    def __init__(self, layout: Layout, delimiter: str = ',', decimal_sep: str = '.') -> None: ...

    def open(self, filename: str, has_header: bool = True) -> bool: ...

    def read_next(self) -> bool: ...

    def close(self) -> None: ...

    def is_open(self) -> bool: ...

    def row_pos(self) -> int: ...

    def file_line(self) -> int: ...

    def layout(self) -> Layout: ...

    def delimiter(self) -> str: ...

    def decimal_separator(self) -> str: ...

    def error_msg(self) -> str: ...

    def read_row(self) -> object: ...

    def read_all(self) -> list: ...

    def __enter__(self) -> CsvReader: ...

    def __exit__(self, *args) -> None: ...

    def __iter__(self) -> CsvReader: ...

    def __next__(self) -> object: ...

class ReaderDirectAccess:
    def __init__(self) -> None: ...

    def open(self, filename: str, rebuild_footer: bool = False) -> bool: ...

    def read(self, index: int) -> list: ...

    def row_count(self) -> int: ...

    def layout(self) -> Layout: ...

    def close(self) -> None: ...

    def is_open(self) -> bool: ...

    def file_flags(self) -> int: ...

    def compression_level(self) -> int: ...

    def version_string(self) -> str: ...

    def creation_time(self) -> int: ...

    def __enter__(self) -> ReaderDirectAccess: ...

    def __exit__(self, *args) -> None: ...

    def __len__(self) -> int: ...

    def __getitem__(self, arg: int, /) -> list: ...

    def __repr__(self) -> str: ...

class SamplerMode(enum.Enum):
    TRUNCATE = 0

    EXPAND = 1

TRUNCATE: SamplerMode = SamplerMode.TRUNCATE

EXPAND: SamplerMode = SamplerMode.EXPAND

class SamplerErrorPolicy(enum.Enum):
    THROW = 0

    SKIP_ROW = 1

    SATURATE = 2

THROW: SamplerErrorPolicy = SamplerErrorPolicy.THROW

SKIP_ROW: SamplerErrorPolicy = SamplerErrorPolicy.SKIP_ROW

SATURATE: SamplerErrorPolicy = SamplerErrorPolicy.SATURATE

class SamplerCompileResult:
    @property
    def success(self) -> bool: ...

    @property
    def error_msg(self) -> str: ...

    @property
    def error_position(self) -> int: ...

    def __bool__(self) -> bool: ...

    def __repr__(self) -> str: ...

class Sampler:
    def __init__(self, reader: Reader) -> None: ...

    def set_conditional(self, expr: str) -> SamplerCompileResult: ...

    def get_conditional(self) -> str: ...

    def set_selection(self, expr: str) -> SamplerCompileResult: ...

    def get_selection(self) -> str: ...

    def set_mode(self, mode: SamplerMode) -> None: ...

    def get_mode(self) -> SamplerMode: ...

    def set_error_policy(self, policy: SamplerErrorPolicy) -> None: ...

    def get_error_policy(self) -> SamplerErrorPolicy: ...

    def output_layout(self) -> Layout: ...

    def next(self) -> bool: ...

    def row(self) -> list: ...

    def source_row_pos(self) -> int: ...

    def bulk(self) -> list: ...

    def is_conditional_passthrough(self) -> bool: ...

    def is_selection_passthrough(self) -> bool: ...

    def window_capacity(self) -> int: ...

    def disassemble(self) -> str: ...

    def __iter__(self) -> Sampler: ...

    def __next__(self) -> object: ...

def read_columns(filename: str) -> dict:
    """
    Read a BCSV file into a dict of numpy arrays (numeric) and lists (strings)
    """

def write_columns(filename: str, columns: dict, col_order: list, col_types: list, row_codec: str = 'delta', compression_level: int = 1, flags: FileFlags = FileFlags.BATCH_COMPRESS) -> None:
    """Write a dict of numpy arrays/lists to a BCSV file"""

def read_to_arrow(filename: str, columns: list | None = None, chunk_size: int = 0) -> object:
    """
    Read a BCSV file into a pyarrow.Table via Arrow C Data Interface (zero-copy).
    Set chunk_size > 0 for chunked reading (returns Table from multiple batches).
    """

def write_from_arrow(filename: str, table: object, row_codec: str = 'delta', compression_level: int = 1, flags: FileFlags = FileFlags.BATCH_COMPRESS) -> None:
    """Write a pyarrow Table/RecordBatch to a BCSV file"""
