/*
 * Copyright (c) 2025-2026 Tobias Weber <weber.tobias.md@gmail.com>
 *
 * This file is part of the BCSV library.
 *
 * Licensed under the MIT License. See LICENSE file in the project root
 * for full license information.
 */

/**
 * @file bcsvCompare.cpp
 * @brief Deterministic file comparison tool for BCSV
 *
 * Compares two BCSV files with combining check modes:
 *   names  - column names must match (header-only)
 *   types  - column types must match (header-only)
 *   values - cell values must match (with cross-type coercion)
 *
 * Modes are combined with commas: --mode "names,types,values" or alias "--mode all".
 *
 * Exit codes: 0 = identical, 1 = different, 2 = error
 */

#include <filesystem>
#include <iostream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <bcsv/bcsv.h>
#include "cli_app.h"
#include "../shared/comparison.h"
#include <sstream>

// ================================================================
// Range specification — shared helper in cli_common.h
// ================================================================

using RangeSpec = bcsv_cli::IndexRangeSet;

/** Parse "0:99,200:-10" → sorted, merged, inclusive ranges.
 * Thin wrapper over bcsv_cli::parseIndexRanges (shared with other tools). */
static RangeSpec parseRanges(const std::string& spec, size_t total) {
    return bcsv_cli::parseIndexRanges(spec, total);
}

// ================================================================
// Config & CheckFlags
// ================================================================

struct CheckFlags {
    bool checkNames     = true;
    bool checkTypes     = true;
    bool checkValues    = true;
    bool stringToValue  = false;
    bool allowImprecise = false;

    bool getCoerce() const noexcept { return checkValues && !checkTypes; }
};

struct Config {
    std::string file_a, file_b;
    CheckFlags  flags;
    double      tolerance = 0.0;
    std::string rows_str, cols_str;
    bool        verbose = false;
};

struct CheckMode {
    bool names = true, types = true, values = true;
};

static CheckMode parseMode(const std::string& spec) {
    CheckMode c;

    if (spec.empty())
        return c;

    if (spec == "all")
        return {true, true, true};
    if (spec == "strict")
        return {true, true, true};
    if (spec == "compatible")
        return {false, true, true};
    if (spec == "value")
        return {false, false, true};

    CheckMode          zeroed{false, false, false};
    std::istringstream iss(spec);
    std::string        token;
    bool               any = false;
    while (std::getline(iss, token, ',')) {
        if (token == "names") {
            zeroed.names = true;
            any          = true;
        } else if (token == "types") {
            zeroed.types = true;
            any          = true;
        } else if (token == "values") {
            zeroed.values = true;
            any           = true;
        } else {
            throw std::runtime_error(
                "Unknown mode '" + token +
                "'. Allowed: names, types, values, all, strict, compatible, value");
        }
    }
    if (!any)
        throw std::runtime_error("Empty mode specification");
    return zeroed;
}

// Usage/help is generated by CLI11 in main() below.

// ================================================================
// Emit result
// ================================================================

static void emitResult(const bcsv_compare::FileComparisonResult& result, bool verbose) {
    if (verbose)
        std::cout << bcsv_compare::formatSummary(result);
}

// ================================================================
// Comparison
// ================================================================

static int compareFiles(const Config& cfg) {
    const auto& f      = cfg.flags;
    bool        coerce = f.getCoerce();

    if (!std::filesystem::exists(cfg.file_a)) {
        std::cerr << "Error: File not found: " << cfg.file_a << "\n";
        return 2;
    }
    if (!std::filesystem::exists(cfg.file_b)) {
        std::cerr << "Error: File not found: " << cfg.file_b << "\n";
        return 2;
    }

    bcsv::ReaderDirectAccess<bcsv::Layout> readerA, readerB;
    if (!readerA.open(cfg.file_a)) {
        std::cerr << "Error: Cannot open: " << cfg.file_a
                  << "\n  " << readerA.getErrorMsg() << "\n";
        return 2;
    }
    if (!readerB.open(cfg.file_b)) {
        std::cerr << "Error: Cannot open: " << cfg.file_b
                  << "\n  " << readerB.getErrorMsg() << "\n";
        readerA.close();
        return 2;
    }

    const auto& layoutA = readerA.layout();
    const auto& layoutB = readerB.layout();
    size_t      ncols   = layoutA.columnCount();

    bcsv_compare::FileComparisonResult result;
    result.identical = true;
    result.tolerance = cfg.tolerance;
    result.mode      = coerce
                           ? bcsv_compare::CompareMode::VALUE
                           : (f.checkNames ? bcsv_compare::CompareMode::STRICT
                                           : bcsv_compare::CompareMode::COMPATIBLE);
    result.rows_a    = readerA.rowCount();
    result.rows_b    = readerB.rowCount();
    result.cols_a    = layoutA.columnCount();
    result.cols_b    = layoutB.columnCount();

    {
        auto lchk = bcsv_compare::compareLayouts(layoutA, layoutB,
                                                 f.checkNames, f.checkTypes);
        result.mismatches.insert(result.mismatches.end(),
                                 lchk.structural.begin(), lchk.structural.end());
        if (!lchk.ok) {
            result.identical = false;
            emitResult(result, cfg.verbose);
            readerA.close();
            readerB.close();
            return 1;
        }
    }

    if (f.checkValues && readerA.rowCount() != readerB.rowCount()) {
        result.identical = false;
        bcsv_compare::Mismatch m;
        m.kind       = bcsv_compare::MismatchKind::ROW_COUNT_MISMATCH;
        m.row        = ~size_t{0};
        m.col        = ~size_t{0};
        m.file_a_val = std::to_string(readerA.rowCount());
        m.file_b_val = std::to_string(readerB.rowCount());
        result.mismatches.push_back(std::move(m));
        emitResult(result, cfg.verbose);
        readerA.close();
        readerB.close();
        return 1;
    }

    if (!f.checkValues) {
        emitResult(result, cfg.verbose);
        readerA.close();
        readerB.close();
        return result.identical ? 0 : 1;
    }

    auto rowSpec     = parseRanges(cfg.rows_str, readerA.rowCount());
    auto colSpec     = parseRanges(cfg.cols_str, ncols);
    auto colsToCheck = colSpec.toIndices(ncols);

    struct ColStrategy {
        size_t                      col;
        bcsv::ColumnType            ta, tb;
        bcsv_compare::CompareTarget target;
    };
    std::vector<ColStrategy> strategies;
    strategies.reserve(colsToCheck.size());

    for (size_t c : colsToCheck) {
        ColStrategy s{c, layoutA.columnType(c), layoutB.columnType(c),
                      bcsv_compare::CompareTarget::MISMATCH};
        s.target = bcsv_compare::promoteType(s.ta, s.tb);
        if (s.target == bcsv_compare::CompareTarget::STR_VS_NUM)
            s.target = f.stringToValue
                           ? bcsv_compare::CompareTarget::STR_VS_NUM
                           : bcsv_compare::CompareTarget::MISMATCH;
        strategies.push_back(std::move(s));
    }

    size_t rowIdx = 0, valMismatchCount = 0;
    size_t maxMismatches = cfg.verbose ? 100 : 10;

    while (readerA.readNext() && readerB.readNext()) {
        if (rowSpec.contains(rowIdx)) {
            for (auto& s : strategies) {
                bool ok = bcsv_compare::compareCellWithStrategy(
                    readerA.row(), s.col,
                    readerB.row(), s.col,
                    s.ta, s.tb, s.target,
                    cfg.tolerance,
                    f.allowImprecise,
                    f.stringToValue);
                if (!ok) {
                    ++valMismatchCount;
                    result.identical              = false;
                    result.total_value_mismatches = valMismatchCount;
                    if (valMismatchCount <= maxMismatches) {
                        bcsv_compare::Mismatch mm;
                        if (coerce) {
                            bcsv_compare::recordValueMismatch(
                                rowIdx, s.col, readerA.row(), readerB.row(),
                                layoutA, layoutB, mm);
                        } else {
                            bcsv_compare::recordStrictValueMismatch(
                                rowIdx, s.col, readerA.row(), readerB.row(),
                                layoutA, mm);
                        }
                        result.mismatches.push_back(std::move(mm));
                    }
                }
            }
        }
        ++rowIdx;
    }

    readerA.close();
    readerB.close();
    emitResult(result, cfg.verbose);
    return result.identical ? 0 : 1;
}

// ================================================================
// Entry
// ================================================================

int main(int argc, char* argv[]) {
    Config      cfg;
    std::string mode_str;

    CLI::App app{"Compare two BCSV files and report whether they are identical.", "bcsvCompare"};
    argv = app.ensure_utf8(argv);
    bcsv_cli::setupVersionFlag(app, bcsv_cli::programName(argv[0]));

    // Positionals kept optional so a missing/absent-file error exits 2
    // (bcsvCompare's convention), not CLI11's required-error code.
    app.add_option("FILE_A", cfg.file_a, "First BCSV file");
    app.add_option("FILE_B", cfg.file_b, "Second BCSV file");
    app.add_option("--mode", mode_str,
                   "Check modes (comma-separated): names,types,values or all/strict/compatible/value");
    app.add_flag("--string-to-value", cfg.flags.stringToValue,
                 "In values mode: parse STRING cells as numbers for comparison");
    app.add_flag("--allow-imprecise", cfg.flags.allowImprecise,
                 "Allow int-vs-float comparison beyond the float mantissa range (>+/-2^53)");
    app.add_option("--tolerance", cfg.tolerance,
                   "Absolute epsilon for float/double (default: 0.0)");
    app.add_option("--rows", cfg.rows_str, "Row indices to compare, e.g. 0:99,-10:");
    app.add_option("--cols", cfg.cols_str, "Column indices to compare");
    app.add_flag("-v,--verbose", cfg.verbose, "Report mismatch details to stdout");

    app.footer(
        "Value coercion rules (when types may differ):\n"
        "  int vs int              cmp_equal — lossless, handles signedness\n"
        "  int32/uint32 vs float/double promote both to double — always exact\n"
        "  int64/uint64 vs float/double promote to double — exact only within +/-2^53\n"
        "  float vs double         widen to double — always exact\n"
        "  string vs string        exact match\n"
        "  string vs numeric       mismatch (unless --string-to-value)\n\n"
        "Exit codes: 0 = identical, 1 = different, 2 = error");

    CLI11_PARSE(app, argc, argv);

    try {
        if (cfg.file_a.empty())
            throw std::runtime_error("FILE_A and FILE_B are required (-h for help)");
        if (cfg.file_b.empty())
            throw std::runtime_error("FILE_B is required");

        if (!mode_str.empty()) {
            auto m                = parseMode(mode_str);
            cfg.flags.checkNames  = m.names;
            cfg.flags.checkTypes  = m.types;
            cfg.flags.checkValues = m.values;
        }

        return compareFiles(cfg);
    } catch (const std::exception& ex) {
        std::cerr << "Error: " << ex.what() << "\n";
        return 2;
    }
}
