/*
 * Copyright (c) 2025-2026 Tobias Weber <weber.tobias.md@gmail.com>
 *
 * This file is part of the BCSV library.
 *
 * Licensed under the MIT License. See LICENSE file in the project root
 * for full license information.
 */

#include <bit>
#include <cerrno>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <iomanip>
#include <iostream>
#include <limits>
#include <string>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>

#include <bcsv/bcsv.h>
#include <bcsv/std_charconv_compat.h>
#include "cli_app.h"
#include "spec_parse.h"
#include "type_probe.h"

namespace fs = std::filesystem;

// Shared probe/cast machinery (moved to type_probe.h; keep local names).
using bcsv_cli::ColumnProbeState;
using bcsv_cli::cellLoses;
using bcsv_cli::coerce;
using bcsv_cli::visitTyped;

// ── Arg error type — exit code 2 ────────────────────────────────────

struct ArgError : std::invalid_argument {
    using std::invalid_argument::invalid_argument;
};

// ── CLI Config ──────────────────────────────────────────────────────

enum class Mode { Scan, Optimize, Dynamic, Static };

struct Config {
    std::string input_file;
    std::string output_file;
    std::string cols_spec;                  // --cols index ranges (auto modes only)
    std::string type_spec;                  // SPEC for --static / --dynamic
    Mode        mode            = Mode::Scan;
    bool        mode_explicit   = false;    // a mode flag was given
    bool        convert         = false;    // resolved: mode applies AND has output
    bool        in_place        = false;    // --in-place
    bool        overwrite       = false;    // --overwrite
    bool        string_to_value = false;    // --string-to-value (auto modes only)
    double      tolerance       = 0.0;      // --tolerance (absolute epsilon)
    bool        json            = false;    // --json
    bool        verbose         = false;
};

// Usage/help is generated by CLI11 in main() below.

// ── Cast plan ───────────────────────────────────────────────────────

struct ColPlan {
    bcsv::ColumnType original  = bcsv::ColumnType::VOID;
    bcsv::ColumnType requested = bcsv::ColumnType::VOID;  // SPEC / auto-derived target
    bcsv::ColumnType effective = bcsv::ColumnType::VOID;  // after dynamic skip
    bool     lossy       = false;   // requested cast loses data
    bool     skipped     = false;   // dynamic kept original because lossy
    uint64_t lossy_cells = 0;       // #cells the cast would lose (scan)
    uint64_t oor         = 0;       // #cells out of target range (scan)
    uint64_t unparseable = 0;       // #non-numeric string cells (scan)
    uint64_t clamped     = 0;       // #cells clamped/rounded (convert)
};

// Parse a type SPEC (map or positional-list form) against `layout` into a
// per-column requested target (== original where unspecified). Thin wrapper
// around the shared bcsv_cli::parseTypeSpec that adds the layout-aware VOID
// validation. Throws ArgError.
static std::vector<bcsv::ColumnType> parseSpec(const std::string&  spec_in,
                                               const bcsv::Layout& layout) {
    const size_t n = layout.columnCount();

    std::vector<std::string> names;
    names.reserve(n);
    for (size_t i = 0; i < n; ++i)
        names.push_back(std::string(layout.columnName(i)));

    std::vector<std::optional<bcsv::ColumnType>> opt;
    try {
        opt = bcsv_cli::parseTypeSpec(spec_in, n, names, /*allow_void=*/true);
    } catch (const std::exception& e) {
        throw ArgError(e.what());
    }

    std::vector<bcsv::ColumnType> req(n);
    for (size_t i = 0; i < n; ++i) {
        req[i] = layout.columnType(i);
        if (!opt[i])
            continue;
        if (*opt[i] == bcsv::ColumnType::VOID && req[i] != bcsv::ColumnType::VOID)
            throw ArgError("Position " + std::to_string(i) + " is 'void' but column is " +
                           bcsv_cli::columnTypeStr(req[i]));
        if (*opt[i] != bcsv::ColumnType::VOID && req[i] == bcsv::ColumnType::VOID)
            throw ArgError("Column " + std::to_string(i) + " is VOID and cannot be cast");
        req[i] = *opt[i];
    }
    return req;
}

// Stream the file and, for every column whose requested target differs from its
// original type, record whether/how much the cast would lose (spec §9).
static void scanForLoss(const std::string&     input,
                        std::vector<ColPlan>&  plan,
                        double                 tol,
                        size_t&                total_rows) {
    bcsv::Reader<bcsv::Layout> reader;
    if (!reader.open(input))
        throw std::runtime_error("Cannot open BCSV file: " + input +
                                 " (" + reader.getErrorMsg() + ")");
    const size_t n = reader.layout().columnCount();
    total_rows     = 0;

    // Read every row (so total_rows is accurate even for a no-op SPEC); the inner
    // loop skips columns whose target equals their original type.
    while (reader.readNext()) {
        ++total_rows;
        for (size_t i = 0; i < n; ++i) {
            ColPlan& c = plan[i];
            if (c.requested == c.original) continue;
            bool lost = false;
            visitTyped(reader.row(), i, c.original, [&](const auto& v) {
                lost = cellLoses(c.requested, v, tol, c.oor, c.unparseable);
            });
            if (lost) { c.lossy = true; ++c.lossy_cells; }
        }
    }
    reader.close();
}

static bool anyNarrowed(const std::vector<ColumnProbeState>& probes) {
    for (const auto& p : probes) {
        if (p.optimal_type != p.original_type)
            return true;
    }
    return false;
}

// ── Scan phase ──────────────────────────────────────────────────────

static std::vector<ColumnProbeState> scanFile(
    const std::string&            input_path,
    const std::string&            cols_spec,
    bool                          stringsToValue,
    double                        tolerance,
    bool                          verbose,
    size_t&                       total_rows_out,
    bcsv::FileFlags&              flags_out,
    uint8_t&                      comp_out,
    uint32_t&                     packet_size_out,
    std::vector<std::string>&     col_names_out,
    std::vector<size_t>&          selected_cols_out,
    bool&                         scope_active_out) {

    bcsv::Reader<bcsv::Layout> reader;
    if (!reader.open(input_path)) {
        throw std::runtime_error("Cannot open BCSV file: " + input_path +
                                 " (" + reader.getErrorMsg() + ")");
    }

    const auto& layout   = reader.layout();
    size_t      num_cols = layout.columnCount();

    // Capture column names now while the reader is open (avoids a second file open)
    col_names_out.reserve(num_cols);
    for (size_t i = 0; i < num_cols; ++i)
        col_names_out.push_back(layout.columnName(i));

    // Resolve the optional --cols selection (index ranges or column names) now
    // that the layout is known. Invalid specs surface as ArgError (exit code 2).
    bcsv_cli::IndexRangeSet ranges;
    try {
        if (!cols_spec.empty())
            ranges = bcsv_cli::parseColumnSelection(cols_spec, num_cols, col_names_out);
    } catch (const std::exception& e) {
        throw ArgError(std::string("--cols: ") + e.what());
    }
    scope_active_out  = ranges.active();
    selected_cols_out = ranges.toIndices(num_cols);

    std::vector<ColumnProbeState> probes(num_cols);
    size_t                        alive_count = 0;

    // Initialise every probe — convert needs original_type for all columns.
    // Only the selected columns are ever probed; the rest keep
    // optimal_type == original_type and are copied verbatim during convert.
    for (size_t i = 0; i < num_cols; ++i)
        probes[i].init(layout.columnType(i), i, stringsToValue, tolerance);
    for (size_t i : selected_cols_out)
        if (probes[i].alive)
            ++alive_count;

    if (verbose) {
        std::cerr << "Scanning file: " << input_path << " ("
                  << num_cols << " columns, " << alive_count << " to probe)" << std::endl;
    }

    size_t total_rows = 0;

    while (reader.readNext() && alive_count > 0) {
        ++total_rows;

        for (size_t i : selected_cols_out) {
            auto& p = probes[i];
            if (!p.alive)
                continue;

            switch (p.original_type) {
                case bcsv::ColumnType::INT8:
                    reader.row().visitConst<int8_t>(i, [&](size_t, const int8_t& v) { p.visitIntegerSigned(static_cast<int64_t>(v)); }, 1);
                    break;
                case bcsv::ColumnType::INT16:
                    reader.row().visitConst<int16_t>(i, [&](size_t, const int16_t& v) { p.visitIntegerSigned(static_cast<int64_t>(v)); }, 1);
                    break;
                case bcsv::ColumnType::INT32:
                    reader.row().visitConst<int32_t>(i, [&](size_t, const int32_t& v) { p.visitIntegerSigned(static_cast<int64_t>(v)); }, 1);
                    break;
                case bcsv::ColumnType::INT64:
                    reader.row().visitConst<int64_t>(i, [&](size_t, const int64_t& v) { p.visitIntegerSigned(v); }, 1);
                    break;
                case bcsv::ColumnType::UINT8:
                    reader.row().visitConst<uint8_t>(i, [&](size_t, const uint8_t& v) { p.visitIntegerUnsigned(static_cast<uint64_t>(v)); }, 1);
                    break;
                case bcsv::ColumnType::UINT16:
                    reader.row().visitConst<uint16_t>(i, [&](size_t, const uint16_t& v) { p.visitIntegerUnsigned(static_cast<uint64_t>(v)); }, 1);
                    break;
                case bcsv::ColumnType::UINT32:
                    reader.row().visitConst<uint32_t>(i, [&](size_t, const uint32_t& v) { p.visitIntegerUnsigned(static_cast<uint64_t>(v)); }, 1);
                    break;
                case bcsv::ColumnType::UINT64:
                    reader.row().visitConst<uint64_t>(i, [&](size_t, const uint64_t& v) { p.visitIntegerUnsigned(v); }, 1);
                    break;
                case bcsv::ColumnType::FLOAT:
                    reader.row().visitConst<float>(i, [&](size_t, const float& v) { p.visitFloat(static_cast<double>(v)); }, 1);
                    break;
                case bcsv::ColumnType::DOUBLE:
                    reader.row().visitConst<double>(i, [&](size_t, const double& v) { p.visitFloat(v); }, 1);
                    break;
                case bcsv::ColumnType::STRING:
                    reader.row().visitConst<std::string>(i, [&](size_t, const std::string& s) { p.visitString(s); }, 1);
                    break;
                default:
                    p.alive = false;
                    --alive_count;
                    break;
            }
        }

        for (size_t i : selected_cols_out) {
            auto& p = probes[i];
            if (!p.alive)
                continue;
            p.rows_probed++;
            p.checkStabilization();
            if (!p.alive)
                --alive_count;
        }

        if (alive_count == 0)
            break;

        if (verbose && (total_rows & 0x3FFF) == 0) {
            std::cerr << "  Scanned " << total_rows << " rows, "
                      << alive_count << " columns still probing..." << std::endl;
        }
    }
    // Capture file metadata while reader is still open
    flags_out       = reader.fileHeader().getFlags();
    comp_out        = reader.fileHeader().getCompressionLevel();
    packet_size_out = reader.fileHeader().getPacketSize();
    reader.close();

    // Empty-column guard
    for (auto& p : probes) {
        if (p.rows_probed == 0) {
            p.optimal_type = p.original_type;
            p.alive        = false;
        }
    }

    total_rows_out = total_rows;
    return probes;
}

// ── Analyze output ──────────────────────────────────────────────────

static bool printAnalysis(
    const std::string&                   input_path,
    const std::vector<std::string>&      col_names,
    const std::vector<ColumnProbeState>& probes,
    size_t                               rows_scanned,
    bcsv::FileFlags                      flags,
    uint8_t                              comp,
    const std::vector<size_t>&           selected_cols,
    bool                                 scope_active,
    bool /*verbose*/) {

    const size_t num_cols = col_names.size();

    // Only the selected columns are reported/counted. selected_cols already
    // holds every in-scope column (all columns when no --cols was given).
    const size_t scope_cols = selected_cols.size();
    const char*  col_word   = scope_active ? "selected columns" : "columns";

    auto names = bcsv_cli::codecNamesFromFlags(flags, comp);

    bool has_narrowed = anyNarrowed(probes);

    std::cout << "bcsvCast: analysis of " << input_path << "\n";
    std::cout << "File codec: " << names.file_codec << " | Row codec: " << names.row_codec
              << " | Compression: " << static_cast<int>(comp) << "\n";

    if (!has_narrowed) {
        // Try to get total row count for early-termination display only when needed
        size_t total_possible = 0;
        try {
            bcsv::ReaderDirectAccess<bcsv::Layout> da;
            if (da.open(input_path)) {
                total_possible = da.rowCount();
            }
        } catch (...) {}

        // Check for early termination: all columns stabilized before EOF, nothing narrowable
        bool early_terminated = total_possible > 0 && rows_scanned < total_possible;

        if (early_terminated) {
            std::cout << "Rows scanned: " << rows_scanned << " (out of " << total_possible
                      << ", terminated early)\n";
            std::cout << "Columns: " << scope_cols << "\n";
            std::cout << "\nAll " << scope_cols << " " << col_word << " are already at their narrowest type.\n";
            std::cout << "No conversion possible.\n";
            return false;
        }

        std::cout << "Rows scanned: " << rows_scanned << ", Columns: " << scope_cols << "\n";
        std::cout << "\nAll " << scope_cols << " " << col_word << " are already at their narrowest type.\n";
        std::cout << "No conversion possible.\n";
        return false;
    }

    std::cout << "Rows scanned: " << rows_scanned << ", Columns: " << scope_cols << "\n";

    // Table widths
    size_t max_idx = 3;
    if (num_cols > 99) {
        max_idx = std::to_string(num_cols - 1).size();
        if (max_idx < 3)
            max_idx = 3;
    }

    size_t max_name = 4;
    for (size_t i : selected_cols) {
        if (col_names[i].size() > max_name)
            max_name = col_names[i].size();
    }

    size_t opt_width = 0;
    for (size_t i : selected_cols) {
        std::string s = bcsv_cli::columnTypeStr(probes[i].optimal_type);
        if (probes[i].optimal_type == probes[i].original_type)
            s += "       (unchanged)";
        if (s.size() > opt_width)
            opt_width = s.size();
    }

    std::cout << "\n"
              << "  " << std::right << std::setw(static_cast<int>(max_idx)) << "Idx"
              << "  " << std::left << std::setw(static_cast<int>(max_name)) << "Name"
              << "  " << std::right << std::setw(8) << "Original"
              << "  " << std::left << std::setw(static_cast<int>(opt_width)) << "Optimal"
              << "\n"
              << "  " << std::string(max_idx, '-')
              << "  " << std::string(max_name, '-')
              << "  " << std::string(8, '-')
              << "  " << std::string(opt_width, '-')
              << "\n";

    size_t narrowable = 0;
    for (size_t i : selected_cols) {
        auto& p = probes[i];
        std::cout << "  " << std::right << std::setw(static_cast<int>(max_idx)) << i
                  << "  " << std::left << std::setw(static_cast<int>(max_name))
                  << col_names[i]
                  << "  " << std::right << std::setw(8)
                  << bcsv_cli::columnTypeStr(p.original_type)
                  << "  ";

        if (p.optimal_type == p.original_type) {
            std::cout << std::left << std::setw(static_cast<int>(opt_width))
                      << bcsv_cli::columnTypeStr(p.optimal_type) << "       (unchanged)";
        } else {
            std::cout << std::left << std::setw(static_cast<int>(opt_width))
                      << bcsv_cli::columnTypeStr(p.optimal_type);
            ++narrowable;
        }
        std::cout << "\n";
    }

    size_t orig_bytes = 0, opt_bytes = 0;
    for (size_t i : selected_cols) {
        orig_bytes += bcsv::sizeOf(probes[i].original_type);
        opt_bytes += bcsv::sizeOf(probes[i].optimal_type);
    }
    double savings_pct = (orig_bytes > 0)
                             ? 100.0 * (1.0 - static_cast<double>(opt_bytes) / static_cast<double>(orig_bytes))
                             : 0.0;

    std::cout << "\nNarrowable columns: " << narrowable << " / " << scope_cols << "\n";
    std::cout << "Max theoretical savings (flat codec): " << std::fixed
              << std::setprecision(1) << savings_pct
              << "% (estimated type widths only)\n";
    std::cout << "\nProvide an OUTPUT_FILE to apply, or use --in-place to overwrite the input.\n";

    return true; // has narrowed columns
}

// ── Convert phase ───────────────────────────────────────────────────

// Apply a resolved plan: copy verbatim when effective==original, else coerce
// (saturating). Accumulates per-column clamp counts into plan[i].clamped.
static void applyPlan(
    const std::string&    input_path,
    const std::string&    output_path,
    std::vector<ColPlan>& plan,
    double                tol,
    bcsv::FileFlags       flags,
    uint8_t               comp_level,
    size_t                block_size_kb,
    bool                  verbose) {

    bcsv::Reader<bcsv::Layout> reader;
    if (!reader.open(input_path)) {
        throw std::runtime_error("Cannot open for conversion: " + input_path +
                                 " (" + reader.getErrorMsg() + ")");
    }

    const auto& src_layout = reader.layout();
    size_t      num_cols   = src_layout.columnCount();

    bcsv::Layout dst_layout;
    for (size_t i = 0; i < num_cols; ++i)
        dst_layout.addColumn({src_layout.columnName(i), plan[i].effective});

    auto names = bcsv_cli::codecNamesFromFlags(flags, comp_level);

    if (verbose) {
        std::cerr << "Converting to: " << output_path << std::endl;
        std::cerr << "Row codec: " << names.row_codec << std::endl;
    }

    size_t total_rows = 0;
    bcsv_cli::withWriter(dst_layout, names.row_codec, [&](auto& writer) {
        writer.open(output_path, true, comp_level, block_size_kb, flags);

        while (reader.readNext()) {
            ++total_rows;
            auto& dst_row = writer.row();

            for (size_t i = 0; i < num_cols; ++i) {
                ColPlan& c = plan[i];

                if (c.effective == c.original) {
                    reader.row().visitConst(i, [&dst_row](size_t col, const auto& val) { dst_row.set(col, val); }, 1);
                    continue;
                }

                const bcsv::ColumnType dst = c.effective;
                visitTyped(reader.row(), i, c.original, [&](const auto& v) {
                    using S = std::decay_t<decltype(v)>;
                    bcsv::ValueType vt;
                    if constexpr (std::is_same_v<S, std::string>) {
                        char*  endptr = nullptr;
                        double d      = std::strtod(v.c_str(), &endptr);
                        if (v.empty() || endptr != v.c_str() + v.size())
                            throw std::runtime_error(
                                "bcsvCast: cannot convert non-numeric string \"" + v +
                                "\" at row " + std::to_string(total_rows) + " to " +
                                bcsv_cli::columnTypeStr(dst));
                        vt = coerce(dst, d, tol, c.clamped);
                    } else {
                        vt = coerce(dst, v, tol, c.clamped);
                    }
                    std::visit([&i, &dst_row](const auto& x) { dst_row.set(i, x); }, vt);
                });
            }
            writer.writeRow();

            if (verbose && (total_rows & 0x3FFF) == 0)
                std::cerr << "  Written " << total_rows << " rows..." << std::endl;
        }

        writer.close();
        if (verbose)
            std::cerr << "  Written " << total_rows << " rows to " << output_path << std::endl;
    });
}

// Build a plan from auto-derived narrowing probes (all lossless).
static std::vector<ColPlan> planFromProbes(const std::vector<ColumnProbeState>& probes) {
    std::vector<ColPlan> plan(probes.size());
    for (size_t i = 0; i < probes.size(); ++i) {
        plan[i].original  = probes[i].original_type;
        plan[i].requested = probes[i].optimal_type;
        plan[i].effective = probes[i].optimal_type;
    }
    return plan;
}

// Report for --static / --dynamic (human-readable; JSON handled in step 7).
static void reportExplicit(const Config&                   config,
                           const std::string&              input,
                           const std::vector<std::string>& names,
                           const std::vector<ColPlan>&     plan,
                           size_t                          rows) {
    std::cout << "bcsvCast: " << (config.mode == Mode::Static ? "static" : "dynamic")
              << " cast of " << input << "\n";
    std::cout << "Rows scanned: " << rows << ", Columns: " << plan.size();
    if (config.tolerance > 0.0)
        std::cout << ", tolerance: " << config.tolerance;
    std::cout << "\n\n";

    size_t changed = 0, skipped = 0, forced = 0;
    for (size_t i = 0; i < plan.size(); ++i) {
        const ColPlan& c = plan[i];
        std::cout << "  " << i << "  " << names[i] << "  "
                  << bcsv_cli::columnTypeStr(c.original) << " -> "
                  << bcsv_cli::columnTypeStr(c.effective);
        if (c.requested == c.original) {
            std::cout << "   (unchanged)";
        } else if (c.skipped) {
            std::cout << "   skipped: lossy (" << c.lossy_cells << " cells)";
            ++skipped;
        } else if (c.lossy) {
            std::cout << "   forced (" << c.lossy_cells << " lossy cells)";
            ++changed;
            ++forced;
        } else {
            std::cout << "   ok";
            ++changed;
        }
        std::cout << "\n";
    }
    std::cout << "\nChanged: " << changed << ", Skipped: " << skipped
              << ", Forced (lossy): " << forced << " / " << plan.size() << "\n";
}

// Machine-readable plan/result on stdout (spec §11.3). Enumerates every column
// so an agent can build a positional list; `suggested_spec` is a ready-to-copy
// map-form SPEC that reproduces the plan.
static void printJson(const Config&                   config,
                      const std::string&              input,
                      const std::vector<std::string>& names,
                      const std::vector<ColPlan>&     plan,
                      size_t                          rows,
                      const std::string&              output,
                      bool                            applied) {
    const char* mode_str = config.mode == Mode::Scan     ? "scan"
                         : config.mode == Mode::Optimize ? "optimize"
                         : config.mode == Mode::Dynamic  ? "dynamic"
                                                         : "static";
    std::string spec;
    bool        any_loss = false;
    for (size_t i = 0; i < plan.size(); ++i) {
        if (plan[i].requested != plan[i].original) {
            if (!spec.empty()) spec += ",";
            spec += std::to_string(i) + "=" +
                    std::string(bcsv_cli::columnTypeStr(plan[i].requested));
        }
        if (plan[i].lossy) any_loss = true;
    }
    const std::string ver = std::to_string(bcsv::VERSION_MAJOR) + "." +
                            std::to_string(bcsv::VERSION_MINOR) + "." +
                            std::to_string(bcsv::VERSION_PATCH);

    std::cout << "{\n"
              << "  \"tool\": \"bcsvCast\",\n"
              << "  \"version\": " << bcsv_cli::jsonStr(ver) << ",\n"
              << "  \"mode\": \"" << mode_str << "\",\n"
              << "  \"input\": " << bcsv_cli::jsonStr(input) << ",\n"
              << "  \"output\": " << (output.empty() ? "null" : bcsv_cli::jsonStr(output)) << ",\n"
              << "  \"applied\": " << (applied ? "true" : "false") << ",\n"
              << "  \"rows_scanned\": " << rows << ",\n"
              << "  \"num_columns\": " << plan.size() << ",\n"
              << "  \"tolerance\": " << config.tolerance << ",\n"
              << "  \"any_loss\": " << (any_loss ? "true" : "false") << ",\n"
              << "  \"suggested_spec\": " << bcsv_cli::jsonStr(spec) << ",\n"
              << "  \"columns\": [";
    for (size_t i = 0; i < plan.size(); ++i) {
        const ColPlan& c           = plan[i];
        const bool     col_applied = applied && (c.effective != c.original);
        const std::string reason =
            c.skipped ? ("skipped: " + std::to_string(c.lossy_cells) + " lossy cells")
                      : (c.requested == c.original ? "unchanged"
                                                   : (c.lossy ? (std::to_string(c.lossy_cells) + " lossy cells")
                                                              : "ok"));
        std::cout << (i ? "," : "") << "\n    {"
                  << "\"index\": " << i
                  << ", \"name\": " << bcsv_cli::jsonStr(names[i])
                  << ", \"original\": " << bcsv_cli::jsonStr(std::string(bcsv_cli::columnTypeStr(c.original)))
                  << ", \"target\": " << bcsv_cli::jsonStr(std::string(bcsv_cli::columnTypeStr(c.requested)))
                  << ", \"bytes_original\": " << bcsv::sizeOf(c.original)
                  << ", \"bytes_target\": " << bcsv::sizeOf(c.requested)
                  << ", \"applied\": " << (col_applied ? "true" : "false")
                  << ", \"lossy\": " << (c.lossy ? "true" : "false")
                  << ", \"clamped_cells\": " << c.clamped
                  << ", \"values_out_of_range\": " << c.oor
                  << ", \"skipped\": " << (c.skipped ? "true" : "false")
                  << ", \"reason\": " << bcsv_cli::jsonStr(reason)
                  << "}";
    }
    std::cout << "\n  ]\n}\n";
}

// Write the plan to `target` crash-safely: convert into a temp file in the target's
// directory, then atomically rename over `target`. Used by both -o and --in-place, so
// a mid-convert failure (e.g. an unparseable forced string) never destroys an existing
// file. The temp lives in the target's directory to keep the rename on one filesystem.
static void writeViaTemp(const std::string&    input,
                         const fs::path&       target,
                         std::vector<ColPlan>& plan,
                         double                tol,
                         bcsv::FileFlags       flags,
                         uint8_t               comp,
                         size_t                block_kb,
                         bool                  verbose) {
    fs::path tmp_path = bcsv_cli::makeTempSibling(target, "bcsvCast");
    try {
        applyPlan(input, tmp_path.string(), plan, tol, flags, comp, block_kb, verbose);
        fs::rename(tmp_path, target);
    } catch (...) {
        if (fs::exists(tmp_path))
            fs::remove(tmp_path);
        throw;
    }
}

// ── Main ────────────────────────────────────────────────────────────

int main(int argc, char* argv[]) {
    Config      config;
    bool        opt_scan = false, opt_optimize = false;
    std::string static_spec, dynamic_spec;

    CLI::App app{"Change BCSV column types (scan / optimize / static / dynamic).", "bcsvCast"};
    argv = app.ensure_utf8(argv);
    bcsv_cli::setupVersionFlag(app, bcsv_cli::programName(argv[0]));

    app.add_option("INPUT_FILE", config.input_file, "Input BCSV file");
    app.add_option("OUTPUT_FILE", config.output_file, "Output BCSV file (an output enables apply)");
    auto* scan_opt   = app.add_flag("--scan", opt_scan,
                                    "Report smallest lossless type per column (read-only)");
    auto* opt_opt    = app.add_flag("--optimize", opt_optimize,
                                    "Auto-derive smallest lossless types and apply");
    auto* static_opt = app.add_option("--static", static_spec,
                                      "Apply SPEC, clamping lossy values (forced)")->type_name("SPEC");
    auto* dyn_opt    = app.add_option("--dynamic", dynamic_spec,
                                      "Apply SPEC per column, skipping any lossy column")->type_name("SPEC");
    app.add_option("-o,--output", config.output_file,
                   "Output BCSV file (alias for the OUTPUT_FILE positional)");
    app.add_flag("--in-place", config.in_place, "Rewrite INPUT_FILE in place (temp + atomic rename)");
    app.add_flag("--overwrite", config.overwrite, "Allow overwriting an existing OUTPUT_FILE");
    app.add_flag("--string-to-value", config.string_to_value,
                 "Let --scan/--optimize consider STRING->numeric (opt-in)");
    app.add_option("--cols", config.cols_spec,
                   "Restrict --scan/--optimize to columns, by index range or name "
                   "(e.g. '0:3,temp,7:-1')");
    app.add_option("--tolerance", config.tolerance,
                   "Absolute epsilon for float/int loss tests")
        ->check(bcsv_cli::validateToleranceArg)
        ->capture_default_str();
    app.add_flag("--json", config.json, "Emit the plan/result as JSON on stdout");
    app.add_flag("-v,--verbose", config.verbose, "Per-column details and progress to stderr");

    app.footer(
        "Modes (choose one; default: --optimize if an output is given, else --scan).\n\n"
        "SPEC (quote it — shells expand unquoted { }):\n"
        "  map form   '0=int32,price=uint64,7:8=float'  (index, i:j range, or name = type)\n"
        "  list form  'int32,uint64,bool,...'           (one type per column, all)\n"
        "  types: bool int8..int64 uint8..uint64 float double string\n"
        "  (numeric-looking column names must be addressed by index)\n\n"
        "Exit codes: 0 = success, 1 = runtime error, 2 = argument error");

    if (auto rc = bcsv_cli::parseHandled(app, argc, argv, 2)) return *rc;

    try {
        // ── Resolve mode (mutually exclusive) ──
        const int modes_given = (scan_opt->count() > 0) + (opt_opt->count() > 0)
                              + (static_opt->count() > 0) + (dyn_opt->count() > 0);
        if (modes_given > 1)
            throw ArgError("Only one mode may be given "
                           "(--scan / --optimize / --static / --dynamic)");
        if (scan_opt->count()) {
            config.mode = Mode::Scan;     config.mode_explicit = true;
        } else if (opt_opt->count()) {
            config.mode = Mode::Optimize; config.mode_explicit = true;
        } else if (static_opt->count()) {
            config.mode = Mode::Static;   config.mode_explicit = true;
            config.type_spec = static_spec;
        } else if (dyn_opt->count()) {
            config.mode = Mode::Dynamic;  config.mode_explicit = true;
            config.type_spec = dynamic_spec;
        }

        // A positional containing '=' is almost always a brace-expanded SPEC
        // (fish/bash split {a=b,c=d} into words).
        for (const std::string* p : {&config.input_file, &config.output_file})
            if (p->find('=') != std::string::npos)
                throw ArgError("Positional argument '" + *p +
                               "' looks like a type SPEC — quote the SPEC and pass it "
                               "with --static/--dynamic (shells expand unquoted { }).");

        if (config.input_file.empty())
            throw ArgError("Input file is required");

        const bool has_output = config.in_place || !config.output_file.empty();

        // Default-mode inference: no explicit mode → optimize when an output path
        // is present (apply), otherwise scan (read-only).
        if (!config.mode_explicit)
            config.mode = has_output ? Mode::Optimize : Mode::Scan;

        // ── Conflict matrix (all → argument error) ──
        if (config.mode == Mode::Scan && has_output)
            throw ArgError("--scan is read-only; use --optimize to apply "
                           "(or drop the output path).");
        if ((config.mode == Mode::Static || config.mode == Mode::Dynamic) &&
            !config.cols_spec.empty())
            throw ArgError("--cols is not allowed with --static/--dynamic; "
                           "the SPEC already defines the column scope.");
        if (config.in_place && !config.output_file.empty())
            throw ArgError("--in-place does not accept an OUTPUT_FILE");

        // Apply when a writing mode has somewhere to write.
        config.convert = (config.mode != Mode::Scan) && has_output;

        if (!fs::exists(config.input_file)) {
            throw std::runtime_error("Input file does not exist: " + config.input_file);
        }

        // A tolerance ≥ 0.5 makes the float→int wholeness test trivially true
        // (every value is within 0.5 of an integer), so it effectively disables it.
        if (config.tolerance >= 0.5)
            std::cerr << "bcsvCast: warning: --tolerance " << config.tolerance
                      << " makes the float->int wholeness test trivially true "
                         "(every value is within 0.5 of an integer)." << std::endl;

        // Warn on inert flag combinations rather than silently ignoring them.
        if (config.string_to_value &&
            (config.mode == Mode::Static || config.mode == Mode::Dynamic))
            std::cerr << "bcsvCast: warning: --string-to-value is ignored with "
                         "--static/--dynamic (it only affects --scan/--optimize)."
                      << std::endl;
        if (config.overwrite && config.in_place)
            std::cerr << "bcsvCast: warning: --overwrite is ignored with --in-place."
                      << std::endl;

        // ── Build the plan (+ file metadata) for the selected mode ──
        size_t                        total_rows   = 0;
        bcsv::FileFlags               flags        = bcsv::FileFlags::NONE;
        uint8_t                       comp         = 0;
        uint32_t                      packet_size  = 0;
        std::vector<std::string>      col_names;
        std::vector<size_t>           selected_cols;
        bool                          scope_active = false;
        std::vector<ColPlan>          plan;
        std::vector<ColumnProbeState> probes;   // auto modes only (feeds printAnalysis)
        const bool explicit_mode =
            (config.mode == Mode::Static || config.mode == Mode::Dynamic);

        if (!explicit_mode) {
            probes = scanFile(config.input_file, config.cols_spec,
                              config.string_to_value, config.tolerance, config.verbose,
                              total_rows, flags, comp, packet_size,
                              col_names, selected_cols, scope_active);
            plan = planFromProbes(probes);
        } else {
            // Read layout + metadata, parse the SPEC, then scan for loss.
            {
                bcsv::Reader<bcsv::Layout> reader;
                if (!reader.open(config.input_file))
                    throw std::runtime_error("Cannot open BCSV file: " + config.input_file +
                                             " (" + reader.getErrorMsg() + ")");
                const auto&  layout = reader.layout();
                const size_t n      = layout.columnCount();
                col_names.reserve(n);
                for (size_t i = 0; i < n; ++i)
                    col_names.push_back(layout.columnName(i));
                auto requested = parseSpec(config.type_spec, layout);   // throws ArgError
                plan.resize(n);
                for (size_t i = 0; i < n; ++i) {
                    plan[i].original  = layout.columnType(i);
                    plan[i].requested = requested[i];
                }
                flags       = reader.fileHeader().getFlags();
                comp        = reader.fileHeader().getCompressionLevel();
                packet_size = reader.fileHeader().getPacketSize();
                reader.close();
            }
            scanForLoss(config.input_file, plan, config.tolerance, total_rows);
            for (auto& c : plan) {
                if (c.requested == c.original) { c.effective = c.original; continue; }
                if (config.mode == Mode::Dynamic) {
                    if (c.lossy) { c.skipped = true; c.effective = c.original; }
                    else           c.effective = c.requested;
                } else {  // Static: apply the requested type, clamping lossy cells.
                    c.effective = c.requested;
                }
            }
            // Fail fast: --static cannot force a non-numeric string to a number, so
            // reject before writing anything (consistent for dry-run and apply).
            if (config.mode == Mode::Static) {
                for (size_t i = 0; i < plan.size(); ++i) {
                    const ColPlan& c = plan[i];
                    if (c.effective != c.original && c.unparseable > 0)
                        throw std::runtime_error(
                            "--static cannot cast column " + std::to_string(i) + " ('" +
                            col_names[i] + "') to " + bcsv_cli::columnTypeStr(c.requested) + ": " +
                            std::to_string(c.unparseable) +
                            " non-numeric string cell(s) — forcing cannot invent a number.");
                }
            }
            for (size_t i = 0; i < plan.size(); ++i) selected_cols.push_back(i);
        }

        // Preserve the source packet/block size (bytes → KB; it was written as
        // blockSizeKB*1024, so this recovers it exactly).  Fall back to the
        // default only for degenerate/zero values.
        const size_t block_size_kb = packet_size >= 1024
                                         ? packet_size / 1024
                                         : bcsv::DEFAULT_PACKET_SIZE_KB;

        // ── Report the plan (human-readable; JSON emitted after any convert) ──
        if (!config.json) {
            // Honest labeling (spec §9.4): a positive tolerance means the "lossless"
            // narrowing may drop up to `tol` per value — say so, so --optimize's
            // report is never mistaken for bit-exact.
            if (!explicit_mode && config.tolerance > 0.0)
                std::cout << "Tolerance: " << config.tolerance
                          << " (values within tolerance are treated as lossless)\n";
            if (!explicit_mode)
                printAnalysis(config.input_file, col_names, probes, total_rows,
                              flags, comp, selected_cols, scope_active, config.verbose);
            else
                reportExplicit(config, config.input_file, col_names, plan, total_rows);
        }

        // Convert phase — apply-always-writes: an output path always produces a
        // file, even when the plan is a no-op (spec §12). Both -o and --in-place go
        // through writeViaTemp (temp + atomic rename) so a mid-convert failure never
        // destroys an existing file.
        if (config.convert) {
            fs::path input_fs(config.input_file);

            if (config.in_place) {
                writeViaTemp(config.input_file, input_fs, plan, config.tolerance,
                             flags, comp, block_size_kb, config.verbose);
                if (config.verbose)
                    std::cerr << "In-place overwrite complete." << std::endl;
            } else {
                const std::string& effective_output = config.output_file;
                fs::path           out_fs(effective_output);

                // Reject same-path: reading and writing the same file corrupts it.
                // Lexical check catches identical / relative-vs-absolute spellings;
                // fs::equivalent (below, once the output exists) catches hard/symlinks.
                if (config.input_file == effective_output ||
                    (fs::current_path() / config.input_file).lexically_normal() ==
                    (fs::current_path() / out_fs).lexically_normal())
                    throw std::runtime_error(
                        "Output path resolves to same file as input: " +
                        effective_output + " — use --in-place to overwrite the input.");

                if (fs::exists(out_fs)) {
                    if (fs::equivalent(input_fs, out_fs))
                        throw std::runtime_error(
                            "Output resolves to the same file as input (hard/symlink): " +
                            effective_output + " — use --in-place to rewrite the input.");
                    if (!fs::is_regular_file(out_fs))
                        throw std::runtime_error(
                            "Output path exists and is not a regular file: " +
                            effective_output);
                    if (!config.overwrite)
                        throw std::runtime_error(
                            "Output file already exists: " + effective_output +
                            " — use --overwrite to replace it.");
                    std::cerr << "Warning: overwriting existing output file: "
                              << effective_output << std::endl;
                }

                writeViaTemp(config.input_file, out_fs, plan, config.tolerance,
                             flags, comp, block_size_kb, config.verbose);
                if (config.verbose)
                    std::cerr << "Converted file written to " << effective_output << std::endl;
            }

            // Per-column clamp / skip notices (stderr) — spec §11.2.
            for (size_t i = 0; i < plan.size(); ++i) {
                const ColPlan& c = plan[i];
                if (c.clamped > 0)
                    std::cerr << "bcsvCast: col " << i << " '" << col_names[i] << "' "
                              << bcsv_cli::columnTypeStr(c.original) << "->"
                              << bcsv_cli::columnTypeStr(c.effective) << ": "
                              << c.clamped << " cells clamped/rounded" << std::endl;
                else if (c.skipped)
                    std::cerr << "bcsvCast: col " << i << " '" << col_names[i] << "' kept "
                              << bcsv_cli::columnTypeStr(c.original) << " (skipped "
                              << bcsv_cli::columnTypeStr(c.requested) << ": "
                              << c.lossy_cells << " lossy cells)" << std::endl;
            }
        }

        // ── JSON output (after any convert, so clamp counts are accurate) ──
        if (config.json) {
            const std::string out_path =
                config.in_place ? config.input_file : config.output_file;
            printJson(config, config.input_file, col_names, plan, total_rows,
                      out_path, config.convert);
        }

        return 0;
    } catch (const ArgError& ex) {
        std::cerr << "Error: " << ex.what() << std::endl;
        return 2;
    } catch (const std::exception& ex) {
        std::cerr << "Error: " << ex.what() << std::endl;
        return 1;
    }
}
